### ISSUE TITLE
Conclusions: ["success"] on dependent jobs including a job with status: "in_progress"

### ISSUE THREAD

**Issue by antifuchs** [technote-space/workflow-conclusion-action#107]
## Describe the bug: バグの概要

We use workflow-conclusion with dependencies on github jobs that get triggered by `workflow_call`. We saw `workflow-conclusion-action@v3` get invoked in a workflow run that had a job fail, but the conclusions array was `["success"]`. The action that failed, however, had `status: 'in_progress',`.

I'm not sure if this is a bug in github actions (why would it invoke a job that needs another, when that other job still has in-progress sub-jobs?), or workflow-conclusion-action (why does it count an in-progress action as a success?

## To Reproduce: 再現手順

I don't have a good reproducer action for this, I'm sorry. This happens irregularly, but the time it happened was exactly when a bad change could get merged into our main branch ):

As a rough outline, we have two workflow_call workflow files, `quick_checks.yml` and `extensive_checks.yml`. These are depended on by our `ci-success` job like this:

```yml
  ci-success:
    runs-on: ubuntu-20.04
    if: always()
    needs:
      - quick_checks
      - extensive_checks
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: fail
        run: |
          echo ${{ env.WORKFLOW_CONCLUSION }}
          exit 1
        if: env.WORKFLOW_CONCLUSION != 'success'
      - name: success
        run: echo success
        if: env.WORKFLOW_CONCLUSION == 'success'
```

## Expected behavior: 期待する動作

I would expect two things:

* No `"in_progress"` jobs to be in the list of jobs that contribute to a conclusion (retry retrieving them if you find one?)
* Only successfully (or unsuccessfully) terminated jobs to contribute to a conclusion.

## Screenshots: スクリーンショット

Redacted screenshot of the job that's "in_progress":
<img width="851" alt="image" src="https://user-images.githubusercontent.com/11864/182932296-b256aab8-b5a7-4c88-806d-c67cb9dfe7ac.png">

Conclusions:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/11864/182932407-3052b17a-ea06-4445-a3ef-24d5c859dced.png">

## Operating environment: バグが発生した環境
 - Version of software
 - OS: [e.g. Windows10]
 - Browser: [e.g. Chrome, Safari]
 - etc.

## Additional context: 補足

I notice that this *feels* like it started happening only when we upgraded to `v3` of workflow-conclusion-action; we were on `v2` before and have downgraded out of caution; it doesn't look like that exhibits the problem, but possibly only insofar as the job that previously failed has `status: 'completed', `
