### ISSUE TITLE
Confusing readme

### ISSUE THREAD

**Issue by glensc** [technote-space/workflow-conclusion-action#45]
the example in readme:

```yaml
      - uses: 8398a7/action-slack@v2
        with:
          # status: ${{ env.WORKFLOW_CONCLUSION }} # neutral, success, cancelled, timed_out, failure
          status: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: env.WORKFLOW_CONCLUSION == 'failure' # notify only if failure
```

why the 'failure' check is declared twice?
1. with status: failure
2. if env.WORKFLOW_CONCLUSION == 'failure'

shouldn't it be sufficient to use only one of them?
