### ISSUE TITLE
すべての job が skipped のときに failure と区別できるようにする

### ISSUE THREAD

**Issue by miyakeryo** [technote-space/workflow-conclusion-action#47]
## Please describe your suggestion: 提案の概要
すべての job が skipped のときに failure になるので、
Skip したのか 失敗したのか判別できない。

## Describe the solution you'd like: 考えうる解決方法
空文字など failure と区別できるようにする

## Describe alternatives you've considered: 考えうる代替案
skip 条件を slack job にも追加することで、skip のときには failure として通知しないことができる。

```yml
  test:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')
    steps:
      - name: Test
        …

  slack:
    name: Slack
    needs: test
    runs-on: ubuntu-latest
#    if: always()
    if: |
      always() &&
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')
    steps:
      - uses: technote-space/workflow-conclusion-action@v1
      - name: Slack Notification on Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        …
```
